[package]
name = "backjoon-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
assert_cmd = "2.0"

[[bin]]
name = "p2557"
path = "bin/p2557.rs"

[[bin]]
name = "p1000"
path = "bin/p1000.rs"

[[bin]]
name = "p1001"
path = "bin/p1001.rs"

